/*
This query creates constraints for Vendor Table
*/
USE Caps_Retail_Company;
DROP TABLE IF EXISTS Inventory;
DROP TABLE IF EXISTS Product;


DROP TABLE IF EXISTS Vendor;
CREATE TABLE Vendor (
VendorID                int                 identity(2000,1),
Vendor_Name             VARCHAR(20)         not null,
Company_Address         VARCHAR(50)         not null,
City                    VARCHAR(20)         not null,
State                   VARCHAR(5)          not null,
Zip                     VARCHAR(10)         not null,
Contact_Person_Name     VARCHAR(20)         null            DEFAULT 'No Name',
Contact_Phone_Number    VARCHAR(15)         null            DEFAULT 'No Phone',
Contact_Email           VARCHAR(30)         null            DEFAULT 'No Email',
-- CONSTRAINTS
CONSTRAINT Vendor_VendorID_pk PRIMARY KEY (VendorID),
);


/* 
This query creates constraints for Product table
*/
USE Caps_Retail_Company;

DROP TABLE IF EXISTS Product;
CREATE TABLE Product (
ProductID		        int                     identity(1000,1), 
Product_Name	        VARCHAR(50)				not null,
Product_Description		Varchar(500)		    null,
Color                   varchar(35)             not null,
Wholesale_Price     	Decimal(9,2)	        not null,
Retail_Price	        Decimal(9,2)	        not null,
VendorID		        int				        not null,
-- CONSTRAINTS
CONSTRAINT Product_ProductID_pk PRIMARY KEY (ProductID),
CONSTRAINT Product_VendorID_fk FOREIGN KEY (VendorID) references Vendor(VendorID)
            on update cascade
		    on delete no action,
);


/*
This query creates constraints for Inventory table
*/
USE Caps_Retail_Company;

DROP TABLE IF EXISTS Inventory;
CREATE TABLE Inventory (
ProductID                   int             not null,
Current_Stock_Level         INT             null,
Reorder_Level               int             null            DEFAULT 2,
Reorder_Quantity            INT             null            DEFAULT 2,
-- CONSTRAINTS
CONSTRAINT Inventory_ProductID_pk PRIMARY KEY (ProductID),
CONSTRAINT Inventory_ProductID_pfk FOREIGN KEY (ProductID) references Product(ProductID)
);

/*
This query insert data values into Vendor table
*/
INSERT INTO Vendor 
(Vendor_Name, Company_Address, City, State, Zip, Contact_Person_Name, Contact_Phone_Number, Contact_Email)
VALUES
('Nike', 'One Bowerman Drive', 'Beaverton',	'OR', '97005', 'Jeff Smith', '(503) 671-6453',	'media.relations@nike.com'),
('Carhartt', '5750 Mercury Drive','Dearborn', 'MI',	'48126', 'Peter Parker', '(800) 833-3118', 'just_ask_us@carhartt.com' ),
('The North Face', '2701 Harbor Bay Pkwy', 'Alameda', 'CA',	'94502', 'Todd Downey', '(888) 863-1968', 'tnfsupport@vfc.com');

/*
This query inserts data into Product Table
*/
INSERT INTO Product 
(Product_Name, Product_Description, Color, Wholesale_Price, Retail_Price, VendorID)
VALUES
('Nike Sphere Dry Cap. 247077', 'Nike Sphere Dry technology ensures maximum moisture control and quick-drying performance. This cap has an unstructured low-profile design with a hook and loop closure. The contrast Swoosh design trademark is embroidered on the bill and center back. Made of 100% polyester. ','Navy', 10.25, 20.5, 2000),
('Nike Sphere Dry Cap. 247077', 'Nike Sphere Dry technology ensures maximum moisture control and quick-drying performance. This cap has an unstructured low-profile design with a hook and loop closure. The contrast Swoosh design trademark is embroidered on the bill and center back. Made of 100% polyester. ','Birch', 10.25, 20.5, 2000),
('Nike Sphere Dry Cap. 247077', 'Nike Sphere Dry technology ensures maximum moisture control and quick-drying performance. This cap has an unstructured low-profile design with a hook and loop closure. The contrast Swoosh design trademark is embroidered on the bill and center back. Made of 100% polyester. ','White', 10.25, 20.5, 2000),
('Nike Sphere Dry Cap. 247077', 'Nike Sphere Dry technology ensures maximum moisture control and quick-drying performance. This cap has an unstructured low-profile design with a hook and loop closure. The contrast Swoosh design trademark is embroidered on the bill and center back. Made of 100% polyester. ','Black', 10.25, 20.5, 2000),
('Nike Swoosh Front Cap. 333114', 'Contrast stitching makes this cap stand out while a water-resistant finish combats moisture. This cap has an unstructured low-profile design and a hook and loop closure. The contrast Swoosh design trademark is embroidered on the front. Made of 100% polyester. ','Black', 10.25, 20.5, 2000),
('Nike Swoosh Front Cap. 333114', 'Contrast stitching makes this cap stand out while a water-resistant finish combats moisture. This cap has an unstructured low-profile design and a hook and loop closure. The contrast Swoosh design trademark is embroidered on the front. Made of 100% polyester. ','Midnight Navy', 10.25, 20.5, 2000),
('Nike Swoosh Front Cap. 333114', 'Contrast stitching makes this cap stand out while a water-resistant finish combats moisture. This cap has an unstructured low-profile design and a hook and loop closure. The contrast Swoosh design trademark is embroidered on the front. Made of 100% polyester. ','Pinenut', 10.25, 20.5, 2000),
('Nike Swoosh Front Cap. 333114', 'Contrast stitching makes this cap stand out while a water-resistant finish combats moisture. This cap has an unstructured low-profile design and a hook and loop closure. The contrast Swoosh design trademark is embroidered on the front. Made of 100% polyester. ','Varsity Royal', 10.25, 20.5, 2000),
('Nike Swoosh Front Cap. 333114', 'Contrast stitching makes this cap stand out while a water-resistant finish combats moisture. This cap has an unstructured low-profile design and a hook and loop closure. The contrast Swoosh design trademark is embroidered on the front. Made of 100% polyester. ','Vivid Green', 9.99, 19.98, 2000),
('Nike Swoosh Front Cap. 333114', 'Contrast stitching makes this cap stand out while a water-resistant finish combats moisture. This cap has an unstructured low-profile design and a hook and loop closure. The contrast Swoosh design trademark is embroidered on the front. Made of 100% polyester. ','White', 10.25, 20.5, 2000),
('Nike Dri-FIT Swoosh Visor. 429466', 'A high-performance three-panel visor built with Dri-FIT moisture management technology. Contrast stitching adds interest while the hook and loop closure ensures a custom fit. The contrast Swoosh design trademark is embroidered on the bill. Front panel measures approximately 1.875 h x 10 w. Made of 100% Dri-FIT polyester twill. ','Black', 9.25, 18.5, 2000),
('Nike Dri-FIT Swoosh Visor. 429466', 'A high-performance three-panel visor built with Dri-FIT moisture management technology. Contrast stitching adds interest while the hook and loop closure ensures a custom fit. The contrast Swoosh design trademark is embroidered on the bill. Front panel measures approximately 1.875 h x 10 w. Made of 100% Dri-FIT polyester twill. ','Navy', 9.25, 18.5, 2000),
('Nike Dri-FIT Swoosh Visor. 429466', 'A high-performance three-panel visor built with Dri-FIT moisture management technology. Contrast stitching adds interest while the hook and loop closure ensures a custom fit. The contrast Swoosh design trademark is embroidered on the bill. Front panel measures approximately 1.875 h x 10 w. Made of 100% Dri-FIT polyester twill. ','White', 9.25, 18.5, 2000),
('Nike Dri-FIT Swoosh Perforated Cap. 429467', 'Maximum breathability is achieved with Dri-FIT moisture management technology and perforated mid and back panels. A contrast underbill reduces sun glare. This 6-panel cap has an unstructured low-profile design with a hook and loop closure. The contrast Swoosh design trademark is embroidered on the bill and center back. Made of 100% Dri-FIT polyester. ','Black', 12.25, 24.5, 2000),
('Nike Dri-FIT Swoosh Perforated Cap. 429467', 'Maximum breathability is achieved with Dri-FIT moisture management technology and perforated mid and back panels. A contrast underbill reduces sun glare. This 6-panel cap has an unstructured low-profile design with a hook and loop closure. The contrast Swoosh design trademark is embroidered on the bill and center back. Made of 100% Dri-FIT polyester. ','Navy', 12.25, 24.5, 2000),
('Nike Dri-FIT Swoosh Perforated Cap. 429467', 'Maximum breathability is achieved with Dri-FIT moisture management technology and perforated mid and back panels. A contrast underbill reduces sun glare. This 6-panel cap has an unstructured low-profile design with a hook and loop closure. The contrast Swoosh design trademark is embroidered on the bill and center back. Made of 100% Dri-FIT polyester. ','White', 12.25, 24.5, 2000),
('Nike Unstructured Twill Cap. 580087', 'The perfect classic look with a contrast underbill as engineered by Nike. This cap has an unstructured mid-profile design and a self-fabric closure with buckle. The contrast Swoosh design trademark is embroidered on the center back. Made of 58/42 cotton/poly twill. ','Deep Black', 7.25, 14.5, 2000),
('Nike Unstructured Twill Cap. 580087', 'The perfect classic look with a contrast underbill as engineered by Nike. This cap has an unstructured mid-profile design and a self-fabric closure with buckle. The contrast Swoosh design trademark is embroidered on the center back. Made of 58/42 cotton/poly twill. ','True White', 7.25, 14.5, 2000),
('Nike Unstructured Twill Cap. 580087', 'The perfect classic look with a contrast underbill as engineered by Nike. This cap has an unstructured mid-profile design and a self-fabric closure with buckle. The contrast Swoosh design trademark is embroidered on the center back. Made of 58/42 cotton/poly twill. ','Deep Navy', 7.25, 14.5, 2000),
('Nike Unstructured Twill Cap. 580087', 'The perfect classic look with a contrast underbill as engineered by Nike. This cap has an unstructured mid-profile design and a self-fabric closure with buckle. The contrast Swoosh design trademark is embroidered on the center back. Made of 58/42 cotton/poly twill. ','Dark Khaki', 7.25, 14.5, 2000),
('Nike Dri-FIT Swoosh Front Cap. 548533', 'The contrast welded Swoosh design trademark takes front and center on this unstructured moisture-wicking cap. A low-profile contrast underbill and hook and loop closure complete this sporty design. Made of 100% Dri-FIT polyester. ','Anthracite/ Black', 10.25, 20.5, 2000),
('Nike Dri-FIT Swoosh Front Cap. 548533', 'The contrast welded Swoosh design trademark takes front and center on this unstructured moisture-wicking cap. A low-profile contrast underbill and hook and loop closure complete this sporty design. Made of 100% Dri-FIT polyester. ','Black/ White', 10.25, 20.5, 2000),
('Nike Dri-FIT Swoosh Front Cap. 548533', 'The contrast welded Swoosh design trademark takes front and center on this unstructured moisture-wicking cap. A low-profile contrast underbill and hook and loop closure complete this sporty design. Made of 100% Dri-FIT polyester. ','Game Royal/ White', 10.25, 20.5, 2000),
('Nike Dri-FIT Swoosh Front Cap. 548533', 'The contrast welded Swoosh design trademark takes front and center on this unstructured moisture-wicking cap. A low-profile contrast underbill and hook and loop closure complete this sporty design. Made of 100% Dri-FIT polyester. ','Lucky Green/ White', 10.25, 20.5, 2000),
('Nike Dri-FIT Swoosh Front Cap. 548533', 'The contrast welded Swoosh design trademark takes front and center on this unstructured moisture-wicking cap. A low-profile contrast underbill and hook and loop closure complete this sporty design. Made of 100% Dri-FIT polyester. ','White/ Black', 10.25, 20.5, 2000),
('Nike Swoosh Legacy 91 Cap. 779797', 'With a smooth front panel and stretch for comfort this moisture-wicking cap continues a legacy of performance. This popular cap has been modernized from its original 1991 design with an unstructured mid-profile and a hook and loop closure. The contrast Swoosh design trademark is embroidered on the bill. Made of 5.6-ounce 90/10 polyester/spandex. ','Cool Grey/ Dark Grey', 11.25, 22.5, 2000),
('Nike Swoosh Legacy 91 Cap. 779797', 'With a smooth front panel and stretch for comfort this moisture-wicking cap continues a legacy of performance. This popular cap has been modernized from its original 1991 design with an unstructured mid-profile and a hook and loop closure. The contrast Swoosh design trademark is embroidered on the bill. Made of 5.6-ounce 90/10 polyester/spandex. ','White/ White', 11.25, 22.5, 2000),
('Nike Swoosh Legacy 91 Cap. 779797', 'With a smooth front panel and stretch for comfort this moisture-wicking cap continues a legacy of performance. This popular cap has been modernized from its original 1991 design with an unstructured mid-profile and a hook and loop closure. The contrast Swoosh design trademark is embroidered on the bill. Made of 5.6-ounce 90/10 polyester/spandex. ','Game Royal/ White', 11.25, 22.5, 2000),
('Nike Swoosh Legacy 91 Cap. 779797', 'With a smooth front panel and stretch for comfort this moisture-wicking cap continues a legacy of performance. This popular cap has been modernized from its original 1991 design with an unstructured mid-profile and a hook and loop closure. The contrast Swoosh design trademark is embroidered on the bill. Made of 5.6-ounce 90/10 polyester/spandex. ','Dark Grey/ White', 11.25, 22.5, 2000),
('Nike Swoosh Legacy 91 Cap. 779797', 'With a smooth front panel and stretch for comfort this moisture-wicking cap continues a legacy of performance. This popular cap has been modernized from its original 1991 design with an unstructured mid-profile and a hook and loop closure. The contrast Swoosh design trademark is embroidered on the bill. Made of 5.6-ounce 90/10 polyester/spandex. ','Black/ Black', 11.25, 22.5, 2000),
('Nike Swoosh Legacy 91 Cap. 779797', 'With a smooth front panel and stretch for comfort this moisture-wicking cap continues a legacy of performance. This popular cap has been modernized from its original 1991 design with an unstructured mid-profile and a hook and loop closure. The contrast Swoosh design trademark is embroidered on the bill. Made of 5.6-ounce 90/10 polyester/spandex. ','Navy/ Navy', 11.25, 22.5, 2000),
('Nike Sphere Dry Cap. 247077', 'Nike Sphere Dry technology ensures maximum moisture control and quick-drying performance. This cap has an unstructured low-profile design with a hook and loop closure. The contrast Swoosh design trademark is embroidered on the bill and center back. Made of 100% polyester. ','Game Royal/ White', 10.25, 20.5, 2000),
('Nike Sphere Dry Cap. 247077', 'Nike Sphere Dry technology ensures maximum moisture control and quick-drying performance. This cap has an unstructured low-profile design with a hook and loop closure. The contrast Swoosh design trademark is embroidered on the bill and center back. Made of 100% polyester. ','Black/ Gym Red', 10.25, 20.5, 2000),
('Nike Sphere Dry Cap. 247077', 'Nike Sphere Dry technology ensures maximum moisture control and quick-drying performance. This cap has an unstructured low-profile design with a hook and loop closure. The contrast Swoosh design trademark is embroidered on the bill and center back. Made of 100% polyester. ','Anthracite/ Anthracite', 10.25, 20.5, 2000),
('Nike Sphere Dry Cap. 247077', 'Nike Sphere Dry technology ensures maximum moisture control and quick-drying performance. This cap has an unstructured low-profile design with a hook and loop closure. The contrast Swoosh design trademark is embroidered on the bill and center back. Made of 100% polyester. ','Black/ White', 10.25, 20.5, 2000),
('Nike Sphere Dry Cap. 247077', 'Nike Sphere Dry technology ensures maximum moisture control and quick-drying performance. This cap has an unstructured low-profile design with a hook and loop closure. The contrast Swoosh design trademark is embroidered on the bill and center back. Made of 100% polyester. ','White/ Black', 10.25, 20.5, 2000),
('Nike Unstructured Twill Cap. 580087', 'The perfect classic look with a contrast underbill as engineered by Nike. This cap has an unstructured mid-profile design and a self-fabric closure with buckle. The contrast Swoosh design trademark is embroidered on the center back. Made of 58/42 cotton/poly twill. ','Mean Green', 6.99, 13.98, 2000),
('Nike Unstructured Twill Cap. 580087', 'The perfect classic look with a contrast underbill as engineered by Nike. This cap has an unstructured mid-profile design and a self-fabric closure with buckle. The contrast Swoosh design trademark is embroidered on the center back. Made of 58/42 cotton/poly twill. ','Fusion Pink', 7.25, 14.5, 2000),
('Nike Unstructured Twill Cap. 580087', 'The perfect classic look with a contrast underbill as engineered by Nike. This cap has an unstructured mid-profile design and a self-fabric closure with buckle. The contrast Swoosh design trademark is embroidered on the center back. Made of 58/42 cotton/poly twill. ','Dark Grey', 7.25, 14.5, 2000),
('Nike Unstructured Twill Cap. 580087', 'The perfect classic look with a contrast underbill as engineered by Nike. This cap has an unstructured mid-profile design and a self-fabric closure with buckle. The contrast Swoosh design trademark is embroidered on the center back. Made of 58/42 cotton/poly twill. ','Game Royal', 7.25, 14.5, 2000),
('Nike Unstructured Twill Cap. 580087', 'The perfect classic look with a contrast underbill as engineered by Nike. This cap has an unstructured mid-profile design and a self-fabric closure with buckle. The contrast Swoosh design trademark is embroidered on the center back. Made of 58/42 cotton/poly twill. ','Gym Red', 7.25, 14.5, 2000),
('Nike Dri-FIT Swoosh Perforated Cap. 429467', 'Maximum breathability is achieved with Dri-FIT moisture management technology and perforated mid and back panels. A contrast underbill reduces sun glare. This 6-panel cap has an unstructured low-profile design with a hook and loop closure. The contrast Swoosh design trademark is embroidered on the bill and center back. Made of 100% Dri-FIT polyester. ','Anthracite', 12.25, 24.5, 2000),
('Nike Dri-FIT Swoosh Perforated Cap. 429467', 'Maximum breathability is achieved with Dri-FIT moisture management technology and perforated mid and back panels. A contrast underbill reduces sun glare. This 6-panel cap has an unstructured low-profile design with a hook and loop closure. The contrast Swoosh design trademark is embroidered on the bill and center back. Made of 100% Dri-FIT polyester. ','Blue Sapphire', 12.25, 24.5, 2000),
('Nike Dri-FIT Swoosh Perforated Cap. 429467', 'Maximum breathability is achieved with Dri-FIT moisture management technology and perforated mid and back panels. A contrast underbill reduces sun glare. This 6-panel cap has an unstructured low-profile design with a hook and loop closure. The contrast Swoosh design trademark is embroidered on the bill and center back. Made of 100% Dri-FIT polyester. ','University Red', 12.25, 24.5, 2000),
('Nike Dri-FIT Swoosh Perforated Cap. 429467', 'Maximum breathability is achieved with Dri-FIT moisture management technology and perforated mid and back panels. A contrast underbill reduces sun glare. This 6-panel cap has an unstructured low-profile design with a hook and loop closure. The contrast Swoosh design trademark is embroidered on the bill and center back. Made of 100% Dri-FIT polyester. ','Lucky Green', 12.25, 24.5, 2000),
('Nike Dri-FIT Tech Cap. NKAA1859', 'This durable lightly structured low-profile ripstop cap delivers ultimate comfort thanks to Dri-FIT moisture-wicking technology embroidered eyelets for enhanced breathability and a soft hook and loop closure. The contrast Swoosh design trademark is embroidered on center back. Made of 91/9 polyester ripstop/spandex. ','Black/ White', 11.25, 22.5, 2000),
('Nike Dri-FIT Tech Cap. NKAA1859', 'This durable lightly structured low-profile ripstop cap delivers ultimate comfort thanks to Dri-FIT moisture-wicking technology embroidered eyelets for enhanced breathability and a soft hook and loop closure. The contrast Swoosh design trademark is embroidered on center back. Made of 91/9 polyester ripstop/spandex. ','White/ Black', 11.25, 22.5, 2000),
('Nike Dri-FIT Tech Cap. NKAA1859', 'This durable lightly structured low-profile ripstop cap delivers ultimate comfort thanks to Dri-FIT moisture-wicking technology embroidered eyelets for enhanced breathability and a soft hook and loop closure. The contrast Swoosh design trademark is embroidered on center back. Made of 91/9 polyester ripstop/spandex. ','Navy/ White', 11.25, 22.5, 2000),
('Nike Dri-FIT Tech Cap. NKAA1859', 'This durable lightly structured low-profile ripstop cap delivers ultimate comfort thanks to Dri-FIT moisture-wicking technology embroidered eyelets for enhanced breathability and a soft hook and loop closure. The contrast Swoosh design trademark is embroidered on center back. Made of 91/9 polyester ripstop/spandex. ','Cool Grey/ White', 11.25, 22.5, 2000),
('Nike Dri-FIT Tech Cap. NKAA1859', 'This durable lightly structured low-profile ripstop cap delivers ultimate comfort thanks to Dri-FIT moisture-wicking technology embroidered eyelets for enhanced breathability and a soft hook and loop closure. The contrast Swoosh design trademark is embroidered on center back. Made of 91/9 polyester ripstop/spandex. ','Photo Blue/ White', 11.25, 22.5, 2000),
('Nike Dri-FIT Tech Cap. NKAA1859', 'This durable lightly structured low-profile ripstop cap delivers ultimate comfort thanks to Dri-FIT moisture-wicking technology embroidered eyelets for enhanced breathability and a soft hook and loop closure. The contrast Swoosh design trademark is embroidered on center back. Made of 91/9 polyester ripstop/spandex. ','Anthracite/ White', 11.25, 22.5, 2000),
('Carhartt Odessa Cap. CT100289', 'This top-selling classic cap is tried-and-true Carhartt. 100% cotton washed canvas Carhartt Force  sweatband fights odors; FastDry  technology wicks away sweat for comfort Lightly structured Mid profile Pre-curved visor Adjustable fit with hook and loop closure Leatherette Carhartt label sewn on front Carhartt embroidered on back ','Carhartt Brown', 10.2, 18.55, 2001),
('Carhartt Odessa Cap. CT100289', 'This top-selling classic cap is tried-and-true Carhartt. 100% cotton washed canvas Carhartt Force  sweatband fights odors; FastDry  technology wicks away sweat for comfort Lightly structured Mid profile Pre-curved visor Adjustable fit with hook and loop closure Leatherette Carhartt label sewn on front Carhartt embroidered on back ','Army Green', 10.2, 18.55, 2001),
('Carhartt Rugged Professional Series Cap. CT103056', 'This all-star canvas hat has stretch technology and a sweat-fighting band. 59/39/2 cotton/poly/spandex with 100% polyester mesh back Carhartt Force  sweatband fights odors; FastDry  technology wicks away sweat for comfort Structured Mid profile Pre-curved visor Adjustable fit with plastic closure Carhartt label sewn on side ','Navy', 10.2, 17, 2001),
('Carhartt Rugged Professional Series Cap. CT103056', 'This all-star canvas hat has stretch technology and a sweat-fighting band. 59/39/2 cotton/poly/spandex with 100% polyester mesh back Carhartt Force  sweatband fights odors; FastDry  technology wicks away sweat for comfort Structured Mid profile Pre-curved visor Adjustable fit with plastic closure Carhartt label sewn on side ','Dark Khaki', 10.2, 17, 2001),
('Carhartt Rugged Professional Series Cap. CT103056', 'This all-star canvas hat has stretch technology and a sweat-fighting band. 59/39/2 cotton/poly/spandex with 100% polyester mesh back Carhartt Force  sweatband fights odors; FastDry  technology wicks away sweat for comfort Structured Mid profile Pre-curved visor Adjustable fit with plastic closure Carhartt label sewn on side ','Black', 10.2, 17, 2001),
('Carhartt Ashland Cap. CT101604', 'Featuring cotton duck construction this cap delivers the incredible toughness you expect from Carhartt. 100% firm hand cotton duck canvas Carhartt Force  sweatband fights odors; FastDry  technology wicks away sweat for comfort Structured High profile Flat brim visor Adjustable fit with plastic closure Carhartt label sewn on front Carhartt embroidered on back ','Black', 11, 20, 2001),
('Carhartt Ashland Cap. CT101604', 'Featuring cotton duck construction this cap delivers the incredible toughness you expect from Carhartt. 100% firm hand cotton duck canvas Carhartt Force  sweatband fights odors; FastDry  technology wicks away sweat for comfort Structured High profile Flat brim visor Adjustable fit with plastic closure Carhartt label sewn on front Carhartt embroidered on back ','Carhartt Brown', 11, 20, 2001),
('Carhartt Ashland Cap. CT101604', 'Featuring cotton duck construction this cap delivers the incredible toughness you expect from Carhartt. 100% firm hand cotton duck canvas Carhartt Force  sweatband fights odors; FastDry  technology wicks away sweat for comfort Structured High profile Flat brim visor Adjustable fit with plastic closure Carhartt label sewn on front Carhartt embroidered on back ','Gravel', 11, 20, 2001),
('Carhartt Fleece Hat. CTA207', 'Wear it with pride. Wear it when the icy wind blows on the job site. 100% polyester fleece for warmth Carhartt label sewn on front ','Black', 8.25, 16.5, 2001),
('Carhartt Fleece Hat. CTA207', 'Wear it with pride. Wear it when the icy wind blows on the job site. 100% polyester fleece for warmth Carhartt label sewn on front ','Charcoal Heather', 8.25, 16.5, 2001),
('Carhartt Fleece Hat. CTA207', 'Wear it with pride. Wear it when the icy wind blows on the job site. 100% polyester fleece for warmth Carhartt label sewn on front ','Dark Brown', 8.25, 16.5, 2001),
('Carhartt Fleece 2-In-1 Headwear. CTA202', 'If you work and play outdoors in the winter you need this 2-in-1 hat and face mask. Hat: 100% polyester fleece for warmth Pull-down face mask: 92/8 poly/spandex Carhartt Force  fabric fights odors; FastDry  technology wicks away sweat for comfort Mask can be tucked up into hat when not in use Carhartt label sewn on front ','Black', 15, 25, 2001),
('Carhartt Fleece 2-In-1 Headwear. CTA202', 'If you work and play outdoors in the winter you need this 2-in-1 hat and face mask. Hat: 100% polyester fleece for warmth Pull-down face mask: 92/8 poly/spandex Carhartt Force  fabric fights odors; FastDry  technology wicks away sweat for comfort Mask can be tucked up into hat when not in use Carhartt label sewn on front ','Charcoal Heather', 15, 25, 2001),
('Carhartt Fleece 2-In-1 Headwear. CTA202', 'If you work and play outdoors in the winter you need this 2-in-1 hat and face mask. Hat: 100% polyester fleece for warmth Pull-down face mask: 92/8 poly/spandex Carhartt Force  fabric fights odors; FastDry  technology wicks away sweat for comfort Mask can be tucked up into hat when not in use Carhartt label sewn on front ','Dark Brown', 15, 25, 2001),
('Carhartt Force Helmet-Liner Mask. CTA267', 'Be warm in the bitter cold. Wicks sweat takes the fight to odor and wins in a technical knockout. 92/8 poly/spandex blend with fleeced interior for comfort and warmth Carhartt Force  fabric fights odors; FastDry  technology wicks away sweat for comfort Full facial protection that extends below the neckline Face mask pulls down below the chin when not needed Flat seam construction enhances comfort Carhartt label printed on front Carhartt Force  logo printed on back ','Black', 15, 25, 2001),
('Carhartt Force Helmet-Liner Mask. CTA267', 'Be warm in the bitter cold. Wicks sweat takes the fight to odor and wins in a technical knockout. 92/8 poly/spandex blend with fleeced interior for comfort and warmth Carhartt Force  fabric fights odors; FastDry  technology wicks away sweat for comfort Full facial protection that extends below the neckline Face mask pulls down below the chin when not needed Flat seam construction enhances comfort Carhartt label printed on front Carhartt Force  logo printed on back ','Shadow', 15, 25, 2001),
('Carhartt Acrylic Knit Hat. CTA205', 'Warm and snug this beanie comes in enough colors to wear a new one every day of the week. 100% acrylic rib knit fabric Traditional beanie styling Carhartt label sewn on front ','Black', 10.2, 17, 2001),
('Carhartt Acrylic Knit Hat. CTA205', 'Warm and snug this beanie comes in enough colors to wear a new one every day of the week. 100% acrylic rib knit fabric Traditional beanie styling Carhartt label sewn on front ','Heather Grey', 10.2, 17, 2001),
('Carhartt Acrylic Knit Hat. CTA205', 'Warm and snug this beanie comes in enough colors to wear a new one every day of the week. 100% acrylic rib knit fabric Traditional beanie styling Carhartt label sewn on front ','Canyon Brown', 10.2, 17, 2001),
('Carhartt Acrylic Knit Hat. CTA205', 'Warm and snug this beanie comes in enough colors to wear a new one every day of the week. 100% acrylic rib knit fabric Traditional beanie styling Carhartt label sewn on front ','Heather Grey/ Coal Heather', 10.2, 17, 2001),
('Carhartt Acrylic Knit Hat. CTA205', 'Warm and snug this beanie comes in enough colors to wear a new one every day of the week. 100% acrylic rib knit fabric Traditional beanie styling Carhartt label sewn on front ','Dark Green', 10.2, 17, 2001),
('Carhartt Acrylic Knit Hat. CTA205', 'Warm and snug this beanie comes in enough colors to wear a new one every day of the week. 100% acrylic rib knit fabric Traditional beanie styling Carhartt label sewn on front ','Navy', 10.2, 17, 2001),
('Carhartt Acrylic Knit Hat. CTA205', 'Warm and snug this beanie comes in enough colors to wear a new one every day of the week. 100% acrylic rib knit fabric Traditional beanie styling Carhartt label sewn on front ','Carhartt Brown', 10.2, 17, 2001),
('Carhartt Cotton Canvas Cap CT103938', 'With its sweat-wicking odor-fighting sweatband this cap is ready to get to work. 100% cotton washed canvas Carhartt Force sweatband fights odors; FastDry technology wicks away sweat for comfort Lightly structuredMid profile Pre-curved visor Adjustable fit with hook and loop closure Carhartt label sewn on side Carhartt embroidered on back ','Black', 10.2, 17, 2001),
('Carhartt Cotton Canvas Cap CT103938', 'With its sweat-wicking odor-fighting sweatband this cap is ready to get to work. 100% cotton washed canvas Carhartt Force sweatband fights odors; FastDry technology wicks away sweat for comfort Lightly structuredMid profile Pre-curved visor Adjustable fit with hook and loop closure Carhartt label sewn on side Carhartt embroidered on back ','Gravel', 10.2, 17, 2001),
('Carhartt Cotton Canvas Cap CT103938', 'With its sweat-wicking odor-fighting sweatband this cap is ready to get to work. 100% cotton washed canvas Carhartt Force sweatband fights odors; FastDry technology wicks away sweat for comfort Lightly structuredMid profile Pre-curved visor Adjustable fit with hook and loop closure Carhartt label sewn on side Carhartt embroidered on back ','Carhartt Brown', 10.2, 17, 2001),
('Carhartt Cotton Canvas Cap CT103938', 'With its sweat-wicking odor-fighting sweatband this cap is ready to get to work. 100% cotton washed canvas Carhartt Force sweatband fights odors; FastDry technology wicks away sweat for comfort Lightly structuredMid profile Pre-curved visor Adjustable fit with hook and loop closure Carhartt label sewn on side Carhartt embroidered on back ','Navy', 10.2, 17, 2001),
('Nike Heritage 86 Cap 102699', 'Made from durable cotton twill this unstructured mid-profile cap has embroidered eyelets for enhanced breathability. Interior taping gives a comfortable fit. Closes with an adjustable self-fabric strap with metal slider. The contrast Swoosh design trademark is embroidered on the left-side middle panel. Made of 100% cotton twill. ','Black', 9.3, 18.6, 2000),
('Nike Heritage 86 Cap 102699', 'Made from durable cotton twill this unstructured mid-profile cap has embroidered eyelets for enhanced breathability. Interior taping gives a comfortable fit. Closes with an adjustable self-fabric strap with metal slider. The contrast Swoosh design trademark is embroidered on the left-side middle panel. Made of 100% cotton twill. ','White', 9.3, 18.6, 2000),
('Nike Heritage 86 Cap 102699', 'Made from durable cotton twill this unstructured mid-profile cap has embroidered eyelets for enhanced breathability. Interior taping gives a comfortable fit. Closes with an adjustable self-fabric strap with metal slider. The contrast Swoosh design trademark is embroidered on the left-side middle panel. Made of 100% cotton twill. ','College Navy', 9.3, 18.6, 2000),
('Nike Heritage 86 Cap 102699', 'Made from durable cotton twill this unstructured mid-profile cap has embroidered eyelets for enhanced breathability. Interior taping gives a comfortable fit. Closes with an adjustable self-fabric strap with metal slider. The contrast Swoosh design trademark is embroidered on the left-side middle panel. Made of 100% cotton twill. ','Game Royal', 9.3, 18.6, 2000),
('Nike Heritage 86 Cap 102699', 'Made from durable cotton twill this unstructured mid-profile cap has embroidered eyelets for enhanced breathability. Interior taping gives a comfortable fit. Closes with an adjustable self-fabric strap with metal slider. The contrast Swoosh design trademark is embroidered on the left-side middle panel. Made of 100% cotton twill. ','Anthracite', 9.3, 18.6, 2000),
('Nike Heritage 86 Cap 102699', 'Made from durable cotton twill this unstructured mid-profile cap has embroidered eyelets for enhanced breathability. Interior taping gives a comfortable fit. Closes with an adjustable self-fabric strap with metal slider. The contrast Swoosh design trademark is embroidered on the left-side middle panel. Made of 100% cotton twill. ','University Red', 9.3, 18.6, 2000),
('Nike Heritage 86 Cap 102699', 'Made from durable cotton twill this unstructured mid-profile cap has embroidered eyelets for enhanced breathability. Interior taping gives a comfortable fit. Closes with an adjustable self-fabric strap with metal slider. The contrast Swoosh design trademark is embroidered on the left-side middle panel. Made of 100% cotton twill. ','Khaki', 9.3, 18.6, 2000),
('Nike Heritage 86 Cap 102699', 'Made from durable cotton twill this unstructured mid-profile cap has embroidered eyelets for enhanced breathability. Interior taping gives a comfortable fit. Closes with an adjustable self-fabric strap with metal slider. The contrast Swoosh design trademark is embroidered on the left-side middle panel. Made of 100% cotton twill. ','Gorge Green', 9.3, 18.6, 2000),
('Nike Heritage 86 Cap 102699', 'Made from durable cotton twill this unstructured mid-profile cap has embroidered eyelets for enhanced breathability. Interior taping gives a comfortable fit. Closes with an adjustable self-fabric strap with metal slider. The contrast Swoosh design trademark is embroidered on the left-side middle panel. Made of 100% cotton twill. ','Apple Green', 9.3, 18.6, 2000),
('Nike Heritage 86 Cap 102699', 'Made from durable cotton twill this unstructured mid-profile cap has embroidered eyelets for enhanced breathability. Interior taping gives a comfortable fit. Closes with an adjustable self-fabric strap with metal slider. The contrast Swoosh design trademark is embroidered on the left-side middle panel. Made of 100% cotton twill. ','Valor Blue', 9.3, 18.6, 2000),
('Nike Heritage 86 Cap 102699', 'Made from durable cotton twill this unstructured mid-profile cap has embroidered eyelets for enhanced breathability. Interior taping gives a comfortable fit. Closes with an adjustable self-fabric strap with metal slider. The contrast Swoosh design trademark is embroidered on the left-side middle panel. Made of 100% cotton twill. ','Court Purple', 9.3, 18.6, 2000),
('Nike Heritage 86 Cap 102699', 'Made from durable cotton twill this unstructured mid-profile cap has embroidered eyelets for enhanced breathability. Interior taping gives a comfortable fit. Closes with an adjustable self-fabric strap with metal slider. The contrast Swoosh design trademark is embroidered on the left-side middle panel. Made of 100% cotton twill. ','Team Maroon', 9.3, 18.6, 2000),
('Nike Heritage 86 Cap 102699', 'Made from durable cotton twill this unstructured mid-profile cap has embroidered eyelets for enhanced breathability. Interior taping gives a comfortable fit. Closes with an adjustable self-fabric strap with metal slider. The contrast Swoosh design trademark is embroidered on the left-side middle panel. Made of 100% cotton twill. ','Deep Maroon', 9.3, 18.6, 2000),
('Nike Heritage 86 Cap 102699', 'Made from durable cotton twill this unstructured mid-profile cap has embroidered eyelets for enhanced breathability. Interior taping gives a comfortable fit. Closes with an adjustable self-fabric strap with metal slider. The contrast Swoosh design trademark is embroidered on the left-side middle panel. Made of 100% cotton twill. ','Desert Orange', 9.3, 18.6, 2000),
('Nike Dry Visor AV9754', 'This lightweight three-panel visor features a pre-curved bill and an interior Dri-FIT performance sweatband that folds down for easy embroidery. Hook and loop with silicone pull tab closure. The contrast Swoosh design trademark is embroidered on the left-side panel. Made of 100% Dri-FIT polyester twill. ','College Navy', 10.8, 21.6, 2000),
('Nike Dry Visor AV9754', 'This lightweight three-panel visor features a pre-curved bill and an interior Dri-FIT performance sweatband that folds down for easy embroidery. Hook and loop with silicone pull tab closure. The contrast Swoosh design trademark is embroidered on the left-side panel. Made of 100% Dri-FIT polyester twill. ','Game Royal', 10.8, 21.6, 2000),
('Nike Dry Visor AV9754', 'This lightweight three-panel visor features a pre-curved bill and an interior Dri-FIT performance sweatband that folds down for easy embroidery. Hook and loop with silicone pull tab closure. The contrast Swoosh design trademark is embroidered on the left-side panel. Made of 100% Dri-FIT polyester twill. ','Anthracite', 10.8, 21.6, 2000),
('Nike Dry Visor AV9754', 'This lightweight three-panel visor features a pre-curved bill and an interior Dri-FIT performance sweatband that folds down for easy embroidery. Hook and loop with silicone pull tab closure. The contrast Swoosh design trademark is embroidered on the left-side panel. Made of 100% Dri-FIT polyester twill. ','Khaki', 10.8, 21.6, 2000),
('Nike Dry Visor AV9754', 'This lightweight three-panel visor features a pre-curved bill and an interior Dri-FIT performance sweatband that folds down for easy embroidery. Hook and loop with silicone pull tab closure. The contrast Swoosh design trademark is embroidered on the left-side panel. Made of 100% Dri-FIT polyester twill. ','University Red', 10.8, 21.6, 2000),
('Nike Dry Visor AV9754', 'This lightweight three-panel visor features a pre-curved bill and an interior Dri-FIT performance sweatband that folds down for easy embroidery. Hook and loop with silicone pull tab closure. The contrast Swoosh design trademark is embroidered on the left-side panel. Made of 100% Dri-FIT polyester twill. ','Gorge Green', 10.8, 21.6, 2000),
('Nike Dry Visor AV9754', 'This lightweight three-panel visor features a pre-curved bill and an interior Dri-FIT performance sweatband that folds down for easy embroidery. Hook and loop with silicone pull tab closure. The contrast Swoosh design trademark is embroidered on the left-side panel. Made of 100% Dri-FIT polyester twill. ','Valor Blue', 10.8, 21.6, 2000),
('Nike Dry Visor AV9754', 'This lightweight three-panel visor features a pre-curved bill and an interior Dri-FIT performance sweatband that folds down for easy embroidery. Hook and loop with silicone pull tab closure. The contrast Swoosh design trademark is embroidered on the left-side panel. Made of 100% Dri-FIT polyester twill. ','Court Purple', 10.8, 21.6, 2000),
('Nike Dry Visor AV9754', 'This lightweight three-panel visor features a pre-curved bill and an interior Dri-FIT performance sweatband that folds down for easy embroidery. Hook and loop with silicone pull tab closure. The contrast Swoosh design trademark is embroidered on the left-side panel. Made of 100% Dri-FIT polyester twill. ','Deep Maroon', 10.8, 21.6, 2000),
('Nike Dry Visor AV9754', 'This lightweight three-panel visor features a pre-curved bill and an interior Dri-FIT performance sweatband that folds down for easy embroidery. Hook and loop with silicone pull tab closure. The contrast Swoosh design trademark is embroidered on the left-side panel. Made of 100% Dri-FIT polyester twill. ','Desert Orange', 10.8, 21.6, 2000),
('Nike Sideline Beanie 867309', 'This warm cuffed beanie is perfect for the stands or the street. The contrast high-density Swoosh design trademark is embroidered on the center front. Made of 100% Dri-FIT acrylic. ','Black', 8.4, 16.8, 2000),
('Nike Sideline Beanie 867309', 'This warm cuffed beanie is perfect for the stands or the street. The contrast high-density Swoosh design trademark is embroidered on the center front. Made of 100% Dri-FIT acrylic. ','Medium Grey', 8.4, 16.8, 2000),
('Nike Featherlight Cap CJ7082', 'Stay cool covered and comfortable in this unstructured low-profile cap. Nike AeroBill technology integrates proprietary lightweight construction with breathable sweat-wicking fabric for enhanced comfort and reduced distraction. A hook and loop closure with pull tab ensures a custom fit. The contrast Swoosh design trademark is embroidered on the left-side middle panel. Made of 100% Dri-FIT polyester twill. ','Black', 14.7, 29.4, 2000),
('Nike Featherlight Cap CJ7082', 'Stay cool covered and comfortable in this unstructured low-profile cap. Nike AeroBill technology integrates proprietary lightweight construction with breathable sweat-wicking fabric for enhanced comfort and reduced distraction. A hook and loop closure with pull tab ensures a custom fit. The contrast Swoosh design trademark is embroidered on the left-side middle panel. Made of 100% Dri-FIT polyester twill. ','White', 14.7, 29.4, 2000),
('Nike Featherlight Cap CJ7082', 'Stay cool covered and comfortable in this unstructured low-profile cap. Nike AeroBill technology integrates proprietary lightweight construction with breathable sweat-wicking fabric for enhanced comfort and reduced distraction. A hook and loop closure with pull tab ensures a custom fit. The contrast Swoosh design trademark is embroidered on the left-side middle panel. Made of 100% Dri-FIT polyester twill. ','College Navy', 14.7, 29.4, 2000),
('Nike Featherlight Cap CJ7082', 'Stay cool covered and comfortable in this unstructured low-profile cap. Nike AeroBill technology integrates proprietary lightweight construction with breathable sweat-wicking fabric for enhanced comfort and reduced distraction. A hook and loop closure with pull tab ensures a custom fit. The contrast Swoosh design trademark is embroidered on the left-side middle panel. Made of 100% Dri-FIT polyester twill. ','Game Royal', 14.7, 29.4, 2000),
('Nike Featherlight Cap CJ7082', 'Stay cool covered and comfortable in this unstructured low-profile cap. Nike AeroBill technology integrates proprietary lightweight construction with breathable sweat-wicking fabric for enhanced comfort and reduced distraction. A hook and loop closure with pull tab ensures a custom fit. The contrast Swoosh design trademark is embroidered on the left-side middle panel. Made of 100% Dri-FIT polyester twill. ','Anthracite', 14.7, 29.4, 2000),
('The North Face Ultimate Trucker Cap. NF0A4VUA', 'Constructed of cotton canvas this cap has a rugged canvas wash for a vintage look. The adjustable snapback closure allows a customized fit while mesh venting and eyelets provide breathability and ventilation on the warmest days. Fabric 100% cotton canvas front panels 100% polyester mesh back panelsStructure Structured Profile MidFeatures Washed-down cotton canvas; contrast embroidered The North Face logo embroidered on left middle panelClosure Adjustable snapback ','Vintage White/ Asphalt Grey', 11.1, 18.5, 2002),
('The North Face Ultimate Trucker Cap. NF0A4VUA', 'Constructed of cotton canvas this cap has a rugged canvas wash for a vintage look. The adjustable snapback closure allows a customized fit while mesh venting and eyelets provide breathability and ventilation on the warmest days. Fabric 100% cotton canvas front panels 100% polyester mesh back panelsStructure Structured Profile MidFeatures Washed-down cotton canvas; contrast embroidered The North Face logo embroidered on left middle panelClosure Adjustable snapback ','TNF Mid Grey Heather/ TNF Black', 11.1, 18.5, 2002),
('The North Face Ultimate Trucker Cap. NF0A4VUA', 'Constructed of cotton canvas this cap has a rugged canvas wash for a vintage look. The adjustable snapback closure allows a customized fit while mesh venting and eyelets provide breathability and ventilation on the warmest days. Fabric 100% cotton canvas front panels 100% polyester mesh back panelsStructure Structured Profile MidFeatures Washed-down cotton canvas; contrast embroidered The North Face logo embroidered on left middle panelClosure Adjustable snapback ','Asphalt Grey/ TNF White', 11.1, 18.5, 2002),
('The North Face Ultimate Trucker Cap. NF0A4VUA', 'Constructed of cotton canvas this cap has a rugged canvas wash for a vintage look. The adjustable snapback closure allows a customized fit while mesh venting and eyelets provide breathability and ventilation on the warmest days. Fabric 100% cotton canvas front panels 100% polyester mesh back panelsStructure Structured Profile MidFeatures Washed-down cotton canvas; contrast embroidered The North Face logo embroidered on left middle panelClosure Adjustable snapback ','TNF Black/ TNF Black', 11.1, 18.5, 2002),
('The North Face Ultimate Trucker Cap. NF0A4VUA', 'Constructed of cotton canvas this cap has a rugged canvas wash for a vintage look. The adjustable snapback closure allows a customized fit while mesh venting and eyelets provide breathability and ventilation on the warmest days. Fabric 100% cotton canvas front panels 100% polyester mesh back panelsStructure Structured Profile MidFeatures Washed-down cotton canvas; contrast embroidered The North Face logo embroidered on left middle panelClosure Adjustable snapback ','Burnt Olive Green/ Asphalt Grey', 11.1, 18.5, 2002),
('The North Face Ultimate Trucker Cap. NF0A4VUA', 'Constructed of cotton canvas this cap has a rugged canvas wash for a vintage look. The adjustable snapback closure allows a customized fit while mesh venting and eyelets provide breathability and ventilation on the warmest days. Fabric 100% cotton canvas front panels 100% polyester mesh back panelsStructure Structured Profile MidFeatures Washed-down cotton canvas; contrast embroidered The North Face logo embroidered on left middle panelClosure Adjustable snapback ','Urban Navy/ TNF White', 11.1, 18.5, 2002),
('The North Face Ultimate Trucker Cap. NF0A4VUA', 'Constructed of cotton canvas this cap has a rugged canvas wash for a vintage look. The adjustable snapback closure allows a customized fit while mesh venting and eyelets provide breathability and ventilation on the warmest days. Fabric 100% cotton canvas front panels 100% polyester mesh back panelsStructure Structured Profile MidFeatures Washed-down cotton canvas; contrast embroidered The North Face logo embroidered on left middle panelClosure Adjustable snapback ','TNF Blue/ TNF Black', 11.1, 18.5, 2002),
('The North Face Ultimate Trucker Cap. NF0A4VUA', 'Constructed of cotton canvas this cap has a rugged canvas wash for a vintage look. The adjustable snapback closure allows a customized fit while mesh venting and eyelets provide breathability and ventilation on the warmest days. Fabric 100% cotton canvas front panels 100% polyester mesh back panelsStructure Structured Profile MidFeatures Washed-down cotton canvas; contrast embroidered The North Face logo embroidered on left middle panelClosure Adjustable snapback ','TNF Black/ TNF White', 11.1, 18.5, 2002),
('The North Face Classic Cap. NF0A4VU9', 'Crafted from 100% recycled fabric for a broken-in look from the start this classic baseball cap keeps up with your outdoor lifestyle. Fabric 100% recycled polyester Structure StructuredProfile MidFeatures Contrast embroidered The North Face logo on left middle panel; woven back label with The North Face logoClosure Adjustable self-fabric strap ','TNF Black', 11.1, 18.5, 2002),
('The North Face Classic Cap. NF0A4VU9', 'Crafted from 100% recycled fabric for a broken-in look from the start this classic baseball cap keeps up with your outdoor lifestyle. Fabric 100% recycled polyester Structure StructuredProfile MidFeatures Contrast embroidered The North Face logo on left middle panel; woven back label with The North Face logoClosure Adjustable self-fabric strap ','Mid Grey', 11.1, 18.5, 2002),
('The North Face Classic Cap. NF0A4VU9', 'Crafted from 100% recycled fabric for a broken-in look from the start this classic baseball cap keeps up with your outdoor lifestyle. Fabric 100% recycled polyester Structure StructuredProfile MidFeatures Contrast embroidered The North Face logo on left middle panel; woven back label with The North Face logoClosure Adjustable self-fabric strap ','Asphalt Grey', 11.1, 18.5, 2002),
('The North Face Classic Cap. NF0A4VU9', 'Crafted from 100% recycled fabric for a broken-in look from the start this classic baseball cap keeps up with your outdoor lifestyle. Fabric 100% recycled polyester Structure StructuredProfile MidFeatures Contrast embroidered The North Face logo on left middle panel; woven back label with The North Face logoClosure Adjustable self-fabric strap ','Urban Navy', 11.1, 18.5, 2002),
('The North Face Classic Cap. NF0A4VU9', 'Crafted from 100% recycled fabric for a broken-in look from the start this classic baseball cap keeps up with your outdoor lifestyle. Fabric 100% recycled polyester Structure StructuredProfile MidFeatures Contrast embroidered The North Face logo on left middle panel; woven back label with The North Face logoClosure Adjustable self-fabric strap ','Timber Tan', 11.1, 18.5, 2002),
('The North Face Classic Cap. NF0A4VU9', 'Crafted from 100% recycled fabric for a broken-in look from the start this classic baseball cap keeps up with your outdoor lifestyle. Fabric 100% recycled polyester Structure StructuredProfile MidFeatures Contrast embroidered The North Face logo on left middle panel; woven back label with The North Face logoClosure Adjustable self-fabric strap ','TNF Blue', 11.1, 18.5, 2002),
('The North Face Mountain Beanie. NF0A4VUB', 'Made of 100% recycled fabric this beanie is made for snow shoveling or just walking in the woods. A fleece liner adds cozy warmth in cold conditions. Fabric 50% recycled polyester body 50% recycled polyester fleece Features Helps reduce landfill waste and the use of virgin materials; woven The North Face logo label ','TNF Black', 9.9, 16.5, 2002),
('The North Face Mountain Beanie. NF0A4VUB', 'Made of 100% recycled fabric this beanie is made for snow shoveling or just walking in the woods. A fleece liner adds cozy warmth in cold conditions. Fabric 50% recycled polyester body 50% recycled polyester fleece Features Helps reduce landfill waste and the use of virgin materials; woven The North Face logo label ','Asphalt Grey', 9.9, 16.5, 2002),
('The North Face Mountain Beanie. NF0A4VUB', 'Made of 100% recycled fabric this beanie is made for snow shoveling or just walking in the woods. A fleece liner adds cozy warmth in cold conditions. Fabric 50% recycled polyester body 50% recycled polyester fleece Features Helps reduce landfill waste and the use of virgin materials; woven The North Face logo label ','TNF Dark Grey Heather', 9.9, 16.5, 2002),
('The North Face Mountain Beanie. NF0A4VUB', 'Made of 100% recycled fabric this beanie is made for snow shoveling or just walking in the woods. A fleece liner adds cozy warmth in cold conditions. Fabric 50% recycled polyester body 50% recycled polyester fleece Features Helps reduce landfill waste and the use of virgin materials; woven The North Face logo label ','Urban Navy', 9.9, 16.5, 2002),
('The North Face Mountain Beanie. NF0A4VUB', 'Made of 100% recycled fabric this beanie is made for snow shoveling or just walking in the woods. A fleece liner adds cozy warmth in cold conditions. Fabric 50% recycled polyester body 50% recycled polyester fleece Features Helps reduce landfill waste and the use of virgin materials; woven The North Face logo label ','TNF Blue', 9.9, 16.5, 2002),
('The North Face Mountain Beanie. NF0A4VUB', 'Made of 100% recycled fabric this beanie is made for snow shoveling or just walking in the woods. A fleece liner adds cozy warmth in cold conditions. Fabric 50% recycled polyester body 50% recycled polyester fleece Features Helps reduce landfill waste and the use of virgin materials; woven The North Face logo label ','Cardinal Red', 9.9, 16.5, 2002),
('The North Face Mountain Beanie. NF0A4VUB', 'Made of 100% recycled fabric this beanie is made for snow shoveling or just walking in the woods. A fleece liner adds cozy warmth in cold conditions. Fabric 50% recycled polyester body 50% recycled polyester fleece Features Helps reduce landfill waste and the use of virgin materials; woven The North Face logo label ','Vintage White', 9.9, 16.5, 2002),
('The North Face Mountain Beanie. NF0A4VUB', 'Made of 100% recycled fabric this beanie is made for snow shoveling or just walking in the woods. A fleece liner adds cozy warmth in cold conditions. Fabric 50% recycled polyester body 50% recycled polyester fleece Features Helps reduce landfill waste and the use of virgin materials; woven The North Face logo label ','Burnt Olive Green', 9.9, 16.5, 2002),
('The North Face Mountain Beanie. NF0A4VUB', 'Made of 100% recycled fabric this beanie is made for snow shoveling or just walking in the woods. A fleece liner adds cozy warmth in cold conditions. Fabric 50% recycled polyester body 50% recycled polyester fleece Features Helps reduce landfill waste and the use of virgin materials; woven The North Face logo label ','Timber Tan', 9.9, 16.5, 2002),
('The North Face Mountain Beanie. NF0A4VUB', 'Made of 100% recycled fabric this beanie is made for snow shoveling or just walking in the woods. A fleece liner adds cozy warmth in cold conditions. Fabric 50% recycled polyester body 50% recycled polyester fleece Features Helps reduce landfill waste and the use of virgin materials; woven The North Face logo label ','Blue Wing', 9.9, 16.5, 2002),
('Carhartt Watch Cap 2.0 CT104597', 'Soft to the touch this timeless cap is stretchy rib knit for a stay-put fit. 100% acrylic stretchable rib knit fabric Carhartt label sewn on left side An updated version of the classic CTA18 Offered in the same colors previously offered in the CTA18 ','Coal Heather', 11.9, 17, 2001),
('Carhartt Watch Cap 2.0 CT104597', 'Soft to the touch this timeless cap is stretchy rib knit for a stay-put fit. 100% acrylic stretchable rib knit fabric Carhartt label sewn on left side An updated version of the classic CTA18 Offered in the same colors previously offered in the CTA18 ','Dark Brown/ Sandstone', 11.9, 17, 2001),
('Carhartt Watch Cap 2.0 CT104597', 'Soft to the touch this timeless cap is stretchy rib knit for a stay-put fit. 100% acrylic stretchable rib knit fabric Carhartt label sewn on left side An updated version of the classic CTA18 Offered in the same colors previously offered in the CTA18 ','Black', 11.9, 17, 2001),
('Carhartt Watch Cap 2.0 CT104597', 'Soft to the touch this timeless cap is stretchy rib knit for a stay-put fit. 100% acrylic stretchable rib knit fabric Carhartt label sewn on left side An updated version of the classic CTA18 Offered in the same colors previously offered in the CTA18 ','Brite Lime', 11.9, 17, 2001),
('Carhartt Watch Cap 2.0 CT104597', 'Soft to the touch this timeless cap is stretchy rib knit for a stay-put fit. 100% acrylic stretchable rib knit fabric Carhartt label sewn on left side An updated version of the classic CTA18 Offered in the same colors previously offered in the CTA18 ','Brite Orange', 11.9, 17, 2001),
('Carhartt Watch Cap 2.0 CT104597', 'Soft to the touch this timeless cap is stretchy rib knit for a stay-put fit. 100% acrylic stretchable rib knit fabric Carhartt label sewn on left side An updated version of the classic CTA18 Offered in the same colors previously offered in the CTA18 ','Navy', 11.9, 17, 2001),
('Carhartt Watch Cap 2.0 CT104597', 'Soft to the touch this timeless cap is stretchy rib knit for a stay-put fit. 100% acrylic stretchable rib knit fabric Carhartt label sewn on left side An updated version of the classic CTA18 Offered in the same colors previously offered in the CTA18 ','Carhartt Brown', 11.9, 17, 2001),
('Carhartt Watch Cap 2.0 CT104597', 'Soft to the touch this timeless cap is stretchy rib knit for a stay-put fit. 100% acrylic stretchable rib knit fabric Carhartt label sewn on left side An updated version of the classic CTA18 Offered in the same colors previously offered in the CTA18 ','Heather Grey', 11.9, 17, 2001),
('Carhartt Watch Cap 2.0 CT104597', 'Soft to the touch this timeless cap is stretchy rib knit for a stay-put fit. 100% acrylic stretchable rib knit fabric Carhartt label sewn on left side An updated version of the classic CTA18 Offered in the same colors previously offered in the CTA18 ','Black/ White', 11.9, 17, 2001),
('Nike Team Beanie. CW6117', 'This warm cuffed beanie is perfect for the stands or the street. The contrast high-density Swoosh logo is embroidered at cuff. Made of 100% Dri-FIT acrylic. ','Anthracite', 9.3, 18.6, 2000),
('Nike Team Beanie. CW6117', 'This warm cuffed beanie is perfect for the stands or the street. The contrast high-density Swoosh logo is embroidered at cuff. Made of 100% Dri-FIT acrylic. ','Black', 9.3, 18.6, 2000),
('Nike Team Beanie. CW6117', 'This warm cuffed beanie is perfect for the stands or the street. The contrast high-density Swoosh logo is embroidered at cuff. Made of 100% Dri-FIT acrylic. ','College Navy', 9.3, 18.6, 2000),
('Nike Team Beanie. CW6117', 'This warm cuffed beanie is perfect for the stands or the street. The contrast high-density Swoosh logo is embroidered at cuff. Made of 100% Dri-FIT acrylic. ','Game Royal', 9.3, 18.6, 2000),
('Nike Team Beanie. CW6117', 'This warm cuffed beanie is perfect for the stands or the street. The contrast high-density Swoosh logo is embroidered at cuff. Made of 100% Dri-FIT acrylic. ','Gorge Green', 9.3, 18.6, 2000),
('Nike Team Beanie. CW6117', 'This warm cuffed beanie is perfect for the stands or the street. The contrast high-density Swoosh logo is embroidered at cuff. Made of 100% Dri-FIT acrylic. ','Medium Grey', 9.3, 18.6, 2000),
('Nike Team Beanie. CW6117', 'This warm cuffed beanie is perfect for the stands or the street. The contrast high-density Swoosh logo is embroidered at cuff. Made of 100% Dri-FIT acrylic. ','University Red', 9.3, 18.6, 2000),
('Carhartt Rugged Professional Series Cap. CT103056', 'This all-star canvas hat has stretch technology and a sweat-fighting band. 59/39/2 cotton/poly/spandex with 100% polyester mesh back Carhartt Force  sweatband fights odors; FastDry  technology wicks away sweat for comfort Structured Mid profile Pre-curved visor Adjustable fit with plastic closure Carhartt label sewn on side ','Shadow Grey', 10.2, 17, 2001),
('Carhartt Knit Insulated Face Mask CT104485', 'Keep your face warm on those brutally cold days when the work still needs to get done. 100% acrylic stretchable rib knit fabric 3M Thinsulate Flex 40-gram insulation for warmth Overlock stitching around eye opening Extra-long neck enhances cold-weather protection Carhartt label sewn on neck ','Black', 15, 25, 2001),
('Carhartt Knit Insulated Face Mask CT104485', 'Keep your face warm on those brutally cold days when the work still needs to get done. 100% acrylic stretchable rib knit fabric 3M Thinsulate Flex 40-gram insulation for warmth Overlock stitching around eye opening Extra-long neck enhances cold-weather protection Carhartt label sewn on neck ','Carhartt Brown', 15, 25, 2001),
('Carhartt Knit Insulated Face Mask CT104485', 'Keep your face warm on those brutally cold days when the work still needs to get done. 100% acrylic stretchable rib knit fabric 3M Thinsulate Flex 40-gram insulation for warmth Overlock stitching around eye opening Extra-long neck enhances cold-weather protection Carhartt label sewn on neck ','Coal Heather', 15, 25, 2001),
('The North Face Truckstop Beanie NF0A5FXY', 'An adjustable cuff means this warm versatile beanie can be worn with a slouchier look. 100% acrylic Adjustable cuff height Woven The North Face fold over label at cuff ','New Taupe Green', 9.9, 16.5, 2002),
('The North Face Truckstop Beanie NF0A5FXY', 'An adjustable cuff means this warm versatile beanie can be worn with a slouchier look. 100% acrylic Adjustable cuff height Woven The North Face fold over label at cuff ','TNF Black', 9.9, 16.5, 2002),
('The North Face Truckstop Beanie NF0A5FXY', 'An adjustable cuff means this warm versatile beanie can be worn with a slouchier look. 100% acrylic Adjustable cuff height Woven The North Face fold over label at cuff ','TNF Black Heather', 9.9, 16.5, 2002),
('The North Face Truckstop Beanie NF0A5FXY', 'An adjustable cuff means this warm versatile beanie can be worn with a slouchier look. 100% acrylic Adjustable cuff height Woven The North Face fold over label at cuff ','Urban Navy Heather', 9.9, 16.5, 2002),
('The North Face Truckstop Beanie NF0A5FXY', 'An adjustable cuff means this warm versatile beanie can be worn with a slouchier look. 100% acrylic Adjustable cuff height Woven The North Face fold over label at cuff ','Asphalt Grey', 9.9, 16.5, 2002),
('The North Face Circular Rib Beanie NF0A7RGH', 'With its circular knit construction this timeless beanie is a cold-weather must-have on the trail or in the streets. An adjustable cuff height leaves your styling options open. A fleece liner helps keep warmth in where you need it most. 100% acrylic Circular rib knit construction with darts for shaping on top of crown Adjustable cuff height Fleece lined Woven The North Face fold over label at cuff ','Asphalt Grey', 9.9, 16.5, 2002),
('The North Face Circular Rib Beanie NF0A7RGH', 'With its circular knit construction this timeless beanie is a cold-weather must-have on the trail or in the streets. An adjustable cuff height leaves your styling options open. A fleece liner helps keep warmth in where you need it most. 100% acrylic Circular rib knit construction with darts for shaping on top of crown Adjustable cuff height Fleece lined Woven The North Face fold over label at cuff ','TNF Black', 9.9, 16.5, 2002),
('The North Face Circular Rib Beanie NF0A7RGH', 'With its circular knit construction this timeless beanie is a cold-weather must-have on the trail or in the streets. An adjustable cuff height leaves your styling options open. A fleece liner helps keep warmth in where you need it most. 100% acrylic Circular rib knit construction with darts for shaping on top of crown Adjustable cuff height Fleece lined Woven The North Face fold over label at cuff ','TNF Medium Grey Heather', 9.9, 16.5, 2002),
('The North Face Circular Rib Beanie NF0A7RGH', 'With its circular knit construction this timeless beanie is a cold-weather must-have on the trail or in the streets. An adjustable cuff height leaves your styling options open. A fleece liner helps keep warmth in where you need it most. 100% acrylic Circular rib knit construction with darts for shaping on top of crown Adjustable cuff height Fleece lined Woven The North Face fold over label at cuff ','TNF Yellow', 9.9, 16.5, 2002),
('The North Face Circular Rib Beanie NF0A7RGH', 'With its circular knit construction this timeless beanie is a cold-weather must-have on the trail or in the streets. An adjustable cuff height leaves your styling options open. A fleece liner helps keep warmth in where you need it most. 100% acrylic Circular rib knit construction with darts for shaping on top of crown Adjustable cuff height Fleece lined Woven The North Face fold over label at cuff ','Urban Navy', 9.9, 16.5, 2002),
('The North Face Pom Beanie NF0A7RGI', 'Complete with a pom this comfortable beanie has a classic look with The North Face sense of adventure. 100% acrylic Thick top pom Woven The North Face fold over label at cuff ','Shady Blue', 11.1, 18.5, 2002),
('The North Face Pom Beanie NF0A7RGI', 'Complete with a pom this comfortable beanie has a classic look with The North Face sense of adventure. 100% acrylic Thick top pom Woven The North Face fold over label at cuff ','TNF Black Heather', 11.1, 18.5, 2002),
('The North Face Pom Beanie NF0A7RGI', 'Complete with a pom this comfortable beanie has a classic look with The North Face sense of adventure. 100% acrylic Thick top pom Woven The North Face fold over label at cuff ','Vintage White', 11.1, 18.5, 2002),
('Nike Dri-FIT Team Visor NKDC4217', 'This lightweight three-panel visor features a pre-curved bill and an interior Dri-FIT performance sweatband that folds down for easy embroidery. Hook and loop closure. The contrast Swoosh logo is embroidered on the left-side panel. Made of 100% Dri-FIT polyester twill.** ','Anthracite', 10.8, 21.6, 2000),
('Nike Dri-FIT Team Visor NKDC4217', 'This lightweight three-panel visor features a pre-curved bill and an interior Dri-FIT performance sweatband that folds down for easy embroidery. Hook and loop closure. The contrast Swoosh logo is embroidered on the left-side panel. Made of 100% Dri-FIT polyester twill.** ','Black', 10.8, 21.6, 2000),
('Nike Dri-FIT Team Visor NKDC4217', 'This lightweight three-panel visor features a pre-curved bill and an interior Dri-FIT performance sweatband that folds down for easy embroidery. Hook and loop closure. The contrast Swoosh logo is embroidered on the left-side panel. Made of 100% Dri-FIT polyester twill.** ','College Navy', 10.8, 21.6, 2000),
('Nike Dri-FIT Team Visor NKDC4217', 'This lightweight three-panel visor features a pre-curved bill and an interior Dri-FIT performance sweatband that folds down for easy embroidery. Hook and loop closure. The contrast Swoosh logo is embroidered on the left-side panel. Made of 100% Dri-FIT polyester twill.** ','Court Purple', 10.8, 21.6, 2000),
('Nike Dri-FIT Team Visor NKDC4217', 'This lightweight three-panel visor features a pre-curved bill and an interior Dri-FIT performance sweatband that folds down for easy embroidery. Hook and loop closure. The contrast Swoosh logo is embroidered on the left-side panel. Made of 100% Dri-FIT polyester twill.** ','Game Royal', 10.8, 21.6, 2000),
('Nike Dri-FIT Team Visor NKDC4217', 'This lightweight three-panel visor features a pre-curved bill and an interior Dri-FIT performance sweatband that folds down for easy embroidery. Hook and loop closure. The contrast Swoosh logo is embroidered on the left-side panel. Made of 100% Dri-FIT polyester twill.** ','Khaki', 10.8, 21.6, 2000),
('Nike Dri-FIT Team Visor NKDC4217', 'This lightweight three-panel visor features a pre-curved bill and an interior Dri-FIT performance sweatband that folds down for easy embroidery. Hook and loop closure. The contrast Swoosh logo is embroidered on the left-side panel. Made of 100% Dri-FIT polyester twill.** ','University Red', 10.8, 21.6, 2000),
('Nike Dri-FIT Team Visor NKDC4217', 'This lightweight three-panel visor features a pre-curved bill and an interior Dri-FIT performance sweatband that folds down for easy embroidery. Hook and loop closure. The contrast Swoosh logo is embroidered on the left-side panel. Made of 100% Dri-FIT polyester twill.** ','Valor Blue', 10.8, 21.6, 2000),
('Nike Dri-FIT Team Visor NKDC4217', 'This lightweight three-panel visor features a pre-curved bill and an interior Dri-FIT performance sweatband that folds down for easy embroidery. Hook and loop closure. The contrast Swoosh logo is embroidered on the left-side panel. Made of 100% Dri-FIT polyester twill.** ','White', 10.8, 21.6, 2000);


/*
This query inserts values into Inventory Table
*/
INSERT INTO Inventory
(ProductID, Current_Stock_Level, Reorder_Level, Reorder_Quantity)
VALUES
(1000, 0, 2, 2),
(1001, 4, 2, 2),
(1002, 3, 2, 2),
(1003, 5, 1, 2),
(1004, 2, 1, 2),
(1005, 5, 2, 2),
(1006, 3, 1, 2),
(1007, 1, 1, 2),
(1008, 3, 1, 2),
(1009, 2, 2, 2),
(1010, 1, 3, 2),
(1011, 3, 3, 2),
(1012, 5, 1, 2),
(1013, 3, 3, 2),
(1014, 1, 2, 2),
(1015, 3, 3, 2),
(1016, 4, 2, 2),
(1017, 2, 1, 2),
(1018, 3, 3, 2),
(1019, 4, 3, 2),
(1020, 5, 2, 2),
(1021, 1, 2, 2),
(1022, 3, 2, 2),
(1023, 5, 2, 2),
(1024, 3, 3, 2),
(1025, 2, 1, 2),
(1026, 1, 1, 2),
(1027, 3, 2, 2),
(1028, 1, 2, 2),
(1029, 4, 1, 2),
(1030, 2, 2, 2),
(1031, 4, 1, 2),
(1032, 4, 1, 2),
(1033, 5, 1, 2),
(1034, 5, 2, 2),
(1035, 2, 1, 2),
(1036, 4, 1, 2),
(1037, 2, 1, 2),
(1038, 3, 3, 2),
(1039, 1, 2, 2),
(1040, 5, 3, 2),
(1041, 2, 2, 2),
(1042, 1, 2, 2),
(1043, 3, 1, 2),
(1044, 1, 1, 2),
(1045, 2, 3, 2),
(1046, 3, 3, 2),
(1047, 3, 3, 2),
(1048, 4, 3, 2),
(1049, 4, 3, 2),
(1050, 5, 3, 2),
(1051, 5, 1, 2),
(1052, 3, 2, 2),
(1053, 1, 1, 2),
(1054, 1, 3, 2),
(1055, 5, 1, 2),
(1056, 1, 2, 2),
(1057, 5, 3, 2),
(1058, 1, 2, 2),
(1059, 4, 1, 2),
(1060, 2, 3, 2),
(1061, 3, 2, 2),
(1062, 3, 3, 2),
(1063, 2, 3, 2),
(1064, 2, 3, 2),
(1065, 5, 3, 2),
(1066, 1, 3, 2),
(1067, 5, 2, 2),
(1068, 0, 0, 0),
(1069, 0, 0, 0),
(1070, 0, 0, 0),
(1071, 4, 3, 2),
(1072, 1, 1, 2),
(1073, 4, 2, 2),
(1074, 1, 2, 2),
(1075, 4, 2, 2),
(1076, 2, 2, 2),
(1077, 2, 2, 2),
(1078, 1, 3, 2),
(1079, 3, 2, 2),
(1080, 5, 1, 2),
(1081, 3, 1, 2),
(1082, 1, 2, 2),
(1083, 4, 2, 2),
(1084, 4, 1, 2),
(1085, 1, 2, 2),
(1086, 4, 3, 2),
(1087, 5, 3, 2),
(1088, 5, 3, 2),
(1089, 2, 3, 2),
(1090, 4, 3, 2),
(1091, 0, 3, 2),
(1092, 3, 3, 2),
(1093, 2, 1, 2),
(1094, 1, 3, 2),
(1095, 5, 2, 2),
(1096, 2, 2, 2),
(1097, 2, 2, 2),
(1098, 2, 1, 2),
(1099, 3, 1, 2),
(1100, 2, 3, 2),
(1101, 3, 2, 2),
(1102, 3, 2, 2),
(1103, 3, 1, 2),
(1104, 5, 1, 2),
(1105, 5, 1, 2),
(1106, 4, 3, 2),
(1107, 4, 3, 2),
(1108, 5, 3, 2),
(1109, 4, 3, 2),
(1110, 3, 1, 2),
(1111, 3, 3, 2),
(1112, 2, 1, 2),
(1113, 3, 3, 2),
(1114, 4, 1, 2),
(1115, 2, 2, 2),
(1116, 3, 2, 2),
(1117, 2, 2, 2),
(1118, 1, 2, 2),
(1119, 2, 2, 2),
(1120, 2, 2, 2),
(1121, 3, 3, 2),
(1122, 4, 2, 2),
(1123, 5, 3, 2),
(1124, 2, 3, 2),
(1125, 2, 1, 2),
(1126, 4, 2, 2),
(1127, 2, 2, 2),
(1128, 3, 1, 2),
(1129, 4, 2, 2),
(1130, 5, 1, 2),
(1131, 2, 1, 2),
(1132, 1, 1, 2),
(1133, 5, 2, 2),
(1134, 2, 1, 2),
(1135, 1, 2, 2),
(1136, 3, 1, 2),
(1137, 4, 1, 2),
(1138, 1, 1, 2),
(1139, 1, 1, 2),
(1140, 1, 2, 2),
(1141, 5, 3, 2),
(1142, 3, 3, 2),
(1143, 2, 1, 2),
(1144, 2, 2, 2),
(1145, 5, 3, 2),
(1146, 2, 2, 2),
(1147, 2, 3, 2),
(1148, 5, 3, 2),
(1149, 3, 2, 2),
(1150, 2, 1, 2),
(1151, 1, 3, 2),
(1152, 3, 3, 2),
(1153, 3, 1, 2),
(1154, 2, 3, 2),
(1155, 5, 2, 2),
(1156, 2, 2, 2),
(1157, 1, 2, 2),
(1158, 2, 3, 2),
(1159, 1, 1, 2),
(1160, 4, 3, 2),
(1161, 2, 1, 2),
(1162, 2, 2, 2),
(1163, 3, 3, 2),
(1164, 1, 1, 2),
(1165, 4, 2, 2),
(1166, 5, 3, 2),
(1167, 1, 3, 2),
(1168, 5, 2, 2),
(1169, 3, 2, 2),
(1170, 4, 2, 2),
(1171, 4, 1, 2),
(1172, 2, 2, 2),
(1173, 2, 1, 2),
(1174, 1, 1, 2);